audio: true
bg_music: 蒙德
frame_scale:
  七七:
  - 60
  - 0.6
  万叶:
  - 60
  - 0.9
  优菈:
  - 60
  - 1.0
  八重神子:
  - 60
  - 1.0
  刻晴:
  - 80
  - 0.8900000000000001
  可莉:
  - 60
  - 0.6
  夜兰:
  - 60
  - 1.0
  宵宫:
  - 60
  - 0.8
  心海:
  - 60
  - 0.8
  早柚:
  - 60
  - 0.6
  珊瑚宫心海:
  - 60
  - 0.8
  班尼特:
  - 60
  - 0.7
  琴:
  - 60
  - 0.8
  甘雨:
  - 60
  - 0.9100000000000001
  神里绫人:
  - 60
  - 1.0
  神里绫华:
  - 60
  - 0.7
  胡桃:
  - 70
  - 0.8
  芭芭拉:
  - 60
  - 0.7
  荒泷一斗:
  - 60
  - 1.0
  莫娜:
  - 60
  - 0.7
  菲谢尔:
  - 60
  - 0.7
  行秋:
  - 60
  - 0.7
  达达利亚:
  - 60
  - 1.0
  迪卢克:
  - 60
  - 1.0
  迪奥娜:
  - 60
  - 0.6
  钟离:
  - 60
  - 1.0
  阿贝多:
  - 60
  - 0.7
  雷电将军:
  - 60
  - 0.9
  魈:
  - 60
  - 0.8
img_path: png
music_path: music
role: 阿贝多
