audio: true
bg_music: 蒙德
frame:
  七七: 50
  万叶: 50
  优菈: 50
  八重神子: 50
  刻晴: 50
  可莉: 50
  夜兰: 50
  宵宫: 50
  心海: 50
  早柚: 50
  珊瑚宫心海: 50
  班尼特: 50
  琴: 50
  甘雨: 50
  神里绫人: 50
  神里绫华: 50
  胡桃: 70
  芭芭拉: 50
  荒泷一斗: 50
  莫娜: 50
  菲谢尔: 50
  行秋: 50
  达达利亚: 50
  迪卢克: 50
  迪奥娜: 50
  钟离: 50
  阿贝多: 50
  雷电将军: 50
  魈: 50
img_path: png
music_path: music
role: 魈
